name: Release image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-docker:
    env:
      tag: ghcr.io/nzws/cargo-cross-image-linux-armv7:latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.tag }}
          cache-from: type=registry,ref=${{ env.tag }}
          cache-to: type=inline
